import React from 'react'
import './xhr-stubs'
import ModuleActions from './actions/modules'
import Modules from './components/modules'

import '../style.css'
import './example.css'
import 'react-publish-toggle/style.css'

React.render(
  <div>
    <h1>react-sortable-item-groups</h1>
    <p>Text generated by <a href="https://www.npmjs.com/package/lorem-hipsum">lorem-hipsum</a>.</p>
    <Modules />
  </div>,
  document.getElementById('example')
)

ModuleActions.load()
